import Head from 'next/head'
import Link from 'next/link'
import { FC } from 'react'
import { Navbar } from '../components/Navbar'
import styles from './Home.module.css'

type MainLayoutProps = {
  children: React.ReactNode;
}

export const MainLayout = ({children}: MainLayoutProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact - Ign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        {children}
      </main>

    </div>
  )
}
